---
- name: Update ~/.gitconfig
  community.general.source_control.git_config:
    name: http.proxy
    scope: global
    value: "{{ proxy_url }}"
  become_user: "{{ item }}"
  loop: "{{ proxy_git_users }}"
