---
- name: Configure PECL with proxy
  ansible.builtin.shell: 
    cmd: "pear config-set http_proxy {{ proxy_url }}"
    executable: /bin/bash
    warn: no
  become_user: "{{ item }}"
  loop: "{{ proxy_pecl_users }}"
  tags: ['molecule-idempotence-notest', 'skip_ansible_lint']
