---
- name: Converge
  hosts: instance
  gather_facts: yes
  remote_user: root

  vars:
    travis_path: "{{ lookup('env', 'TRAVIS_BUILD_DIR') }}"
    vagrant_path: "{{ lookup('env', 'HOME') }}/ansible-configure-http-proxy"
    proxy_ip: proxy
    proxy_port: 3128
    proxy_env:
      HTTP_PROXY: http://{{ proxy_ip }}:{{ proxy_port }}
      HTTPS_PROXY: https://{{ proxy_ip }}:{{ proxy_port }}

  environment: "{{ proxy_env }}"

  pre_tasks:
    - name: Debug environment variables
      debug:
        msg:
          "ansible_env": "{{ ansible_env }}"
        verbosity: 1

    # For Debian-based systems python-apt package must be installed on targeted hosts.
    # https://docs.ansible.com/ansible/latest/modules/package_facts_module.html
    - name: Install python dependencies
      apt:
        name: 
          - python3-apt
          - python-setuptools
        state: present
        update_cache: yes # ensure apt cache is up-to-date before nodejs role attempts to install additionnal packages such as gnupg2

    - name: Install php-pear for testing purposes
      apt:
        name:
          - php-cli
          - php-pear
        state: present

    - name: Ensure wget is present
      apt:
        name: wget
        state: present
      
  roles:
    - name: geerlingguy.nodejs
      vars: 
        npm_config_prefix: "/usr/local/lib/npm"
        npm_config_unsafe_perm: "true"
      tags: ['dependencies', 'molecule-idempotence-notest']
    - role: geerlingguy.git
      tags: ['dependencies', 'molecule-idempotence-notest']
    - role: geerlingguy.pip
      tags: ['dependencies', 'molecule-idempotence-notest']
    - name: "{{ travis_path if travis_path else vagrant_path }}" # finally invoke role
