---
- name: Converge
  hosts: instance
  gather_facts: yes
  remote_user: root
  environment: "{{ proxy_env }}"

  pre_tasks:
    - name: Debug environment variables
      ansible.builtin.debug:
        msg:
          "ansible_env": "{{ ansible_env }}"
          "proxy_env": "{{ proxy_env }}"
        verbosity: 1

  roles:
    - name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}" # finally invoke role
