---
- name: Verify
  hosts: instance
  gather_facts: no
  environment: "{{ proxy_env }}"

  tasks:
    - name: Ensure curl proxy config exists
      block:
        - name: Check for .curlrc config
          stat:
            path: /root/.curlrc
          register: curlrc_output

        - name: Ensure file is present 
          assert:
            that: curlrc_output.stat.exists

    - name: Run curl
      shell:
        cmd: curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
        executable: /bin/bash
        warn: no
      register: curl_output

    - name: Ensure curl returned ok
      assert:
        that: curl_output.rc == 0

    - name: Run the equivalent of "apt-get update"
      apt:
        update_cache: yes

    - name: Ensure npm proxy config exists
      block:
        - name: Check for npm config
          stat:
            path: /root/.npmrc
          register: npmrc_output

        - name: Ensure file is present 
          assert:
            that: npmrc_output.stat.exists

    - name: Update npm using npm itself
      npm:
        name: npm
        global: yes
        state: latest
      tags: ['skip_ansible_lint']

    - name: Run git clone using HTTPS protocol
      git:
        repo: https://github.com/ansible/awx.git
        dest: /opt/awx
        version: 19.3.0

    - name: Run pip install --upgrade
      pip:
        name: pip
        state: latest

    - name: Update PECL channel
      shell: 
        cmd: pecl channel-update pecl.php.net
        executable: /bin/bash
        warn: no

    - name: Check squid access logs
      shell: 
        cmd: grep -q '{{ item }}' /var/log/squid/access.log
        executable: /bin/bash
        warn: no
      become: yes
      loop: 
        - github
        - pecl
        - npmjs
        - pypi.org
        - get.docker.com
      delegate_to: 127.0.0.1 # Inspect local copy of access.log accesible via bind-mount volume
