---
- name: Verify
  hosts: instance
  gather_facts: yes
  environment: "{{ proxy_env }}"

  tasks:
    - name: Ensure apt proxy config exists
      block:
        - name: Check for proxy.conf
          ansible.builtin.stat:
            path: /etc/apt/apt.conf.d/proxy.conf
          register: apt_output

        - name: Ensure file is present 
          ansible.builtin.assert:
            that: apt_output.stat.exists

    - name: Ensure curl proxy config exists
      block:
        - name: Check for .curlrc config
          ansible.builtin.stat:
            path: /root/.curlrc
          register: curlrc_output

        - name: Ensure file is present 
          ansible.builtin.assert:
            that: curlrc_output.stat.exists

    - name: Run curl
      ansible.builtin.shell:
        cmd: curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
        executable: /bin/bash
        warn: no
      register: curl_output

    - name: Ensure curl returned ok
      ansible.builtin.assert:
        that: curl_output.rc == 0

    - name: Run wget
      ansible.builtin.shell:
        cmd: wget https://get.docker.com -O /tmp/get-docker.sh
        executable: /bin/bash
        warn: no
      register: wget_output

    - name: Ensure wget returned ok
      ansible.builtin.assert:
        that: wget_output.rc == 0

    - name: Run the equivalent of "apt-get update"
      ansible.builtin.apt:
        update_cache: yes
        force_apt_get: yes

    - name: Ensure npm proxy config exists
      block:
        - name: Check for npm config
          ansible.builtin.stat:
            path: /root/.npmrc
          register: npmrc_output

        - name: Ensure file is present 
          ansible.builtin.assert:
            that: npmrc_output.stat.exists

    - name: Update npm using npm itself
      npm:
        name: npm
        global: yes
        state: latest
      tags: ['skip_ansible_lint']

    - name: Run git clone using HTTPS protocol
      ansible.builtin.git:
        repo: https://github.com/ansible/awx.git
        dest: /opt/awx
        version: 19.3.0

    - name: Update PECL channel
      ansible.builtin.shell: 
        cmd: pecl channel-update pecl.php.net
        executable: /bin/bash
        warn: no

    - name: Check squid access logs
      ansible.builtin.shell: 
        cmd: grep -q '{{ item }}' /var/log/squid/access.log
        executable: /bin/bash
        warn: no
      become: yes
      loop: 
        - get.docker.com
        - "{{ ansible_distribution_release }}"
        - github.com
        - registry.npmjs.org
        - pecl.php.net
      delegate_to: 127.0.0.1 # Inspect local copy of access.log accesible via bind-mount volume
